name: Build and Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Test syntax
      run: |
        python -m py_compile toAss.py
        echo "✓ Syntax check passed"

  build-windows:
    needs: test
    runs-on: windows-latest
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5==5.15.10 pysubs2==1.8.0 requests==2.31.0 pyinstaller==6.3.0
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name "SRT转ASS字幕转换器" toAss.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/SRT转ASS字幕转换器.exe

  build-macos:
    needs: test
    runs-on: macos-latest
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5==5.15.10 pysubs2==1.8.0 requests==2.31.0 pyinstaller==6.3.0
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name "SRT转ASS字幕转换器" toAss.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-executable
        path: dist/SRT转ASS字幕转换器

  build-linux:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0 xvfb
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5==5.15.10 pysubs2==1.8.0 requests==2.31.0 pyinstaller==6.3.0
    - name: Build executable
      run: |
        xvfb-run -a pyinstaller --onefile --name "SRT转ASS字幕转换器" toAss.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-executable
        path: dist/SRT转ASS字幕转换器

  release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ## SRT转ASS字幕转换器 ${{ github.ref_name }}

          ### 功能特性
          - 支持 SRT → ASS 转换
          - 支持 VTT → ASS 转换
          - 支持 ASS → ASS 样式修改
          - 支持繁体中文转换
          - 支持自定义字幕样式和颜色
          - 支持批量文件处理
          - 现代化的用户界面

          ### 下载说明
          - Windows: 下载 `SRT转ASS字幕转换器.exe`
          - macOS: 下载 `SRT转ASS字幕转换器`
          - Linux: 下载 `SRT转ASS字幕转换器`
        files: |
          artifacts/windows-executable/*
          artifacts/macos-executable/*
          artifacts/linux-executable/*

