name: Build and Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Test syntax
      run: |
        python -m py_compile toAss.py
        echo "✓ Syntax check passed"

  build-windows:
    needs: test
    runs-on: windows-latest
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5==5.15.10 pysubs2==1.8.0 requests==2.31.0 pyinstaller==6.3.0
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name "SRT-to-ASS-Converter" toAss.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/SRT-to-ASS-Converter.exe

  build-macos:
    needs: test
    runs-on: macos-latest
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5==5.15.10 pysubs2==1.8.0 requests==2.31.0 pyinstaller==6.3.0
    - name: Build executable
      run: |
        pyinstaller --onedir --noconsole --name "SRT-to-ASS-Converter" toAss.py
        # Create .app bundle
        mkdir -p "dist/SRT-to-ASS-Converter.app/Contents/MacOS"
        mkdir -p "dist/SRT-to-ASS-Converter.app/Contents/Resources"

        # Copy the executable
        cp -r "dist/SRT-to-ASS-Converter/"* "dist/SRT-to-ASS-Converter.app/Contents/MacOS/"

        # Create Info.plist
        cat > "dist/SRT-to-ASS-Converter.app/Contents/Info.plist" << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>SRT-to-ASS-Converter</string>
            <key>CFBundleIdentifier</key>
            <string>com.senvenluckys.srt-to-ass-converter</string>
            <key>CFBundleName</key>
            <string>SRT to ASS Converter</string>
            <key>CFBundleVersion</key>
            <string>1.0.8</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.8</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>LSMinimumSystemVersion</key>
            <string>10.13.0</string>
        </dict>
        </plist>
        EOF

        # Create a zip file for easier distribution
        cd dist && zip -r "SRT-to-ASS-Converter-macOS.zip" "SRT-to-ASS-Converter.app"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-executable
        path: dist/SRT-to-ASS-Converter-macOS.zip

# Linux构建暂时跳过，避免依赖问题
  # build-linux:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   if: startsWith(github.ref, 'refs/tags/v')
  #
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.11'
  #   - name: Install system dependencies
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install -y libgl1-mesa-dev libglib2.0-0 xvfb
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install PyQt5==5.15.10 pysubs2==1.8.0 requests==2.31.0 pyinstaller==6.3.0
  #   - name: Build executable
  #     run: |
  #       xvfb-run -a pyinstaller --onefile --name "SRT转ASS字幕转换器" toAss.py
  #   - name: Upload artifact
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: linux-executable
  #       path: dist/SRT转ASS字幕转换器

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ## SRT转ASS字幕转换器 ${{ github.ref_name }}

          ### 功能特性
          - 支持 SRT → ASS 转换
          - 支持 VTT → ASS 转换
          - 支持 ASS → ASS 样式修改
          - 支持繁体中文转换
          - 支持自定义字幕样式和颜色
          - 支持批量文件处理
          - 现代化的用户界面

          ### 下载说明
          - Windows: 下载 `SRT-to-ASS-Converter.exe`，双击运行
          - macOS: 下载 `SRT-to-ASS-Converter-macOS.zip`，解压后双击 `.app` 文件运行
          - Linux: 请从源码运行 `python toAss.py`

          ### Linux用户安装说明
          ```bash
          git clone https://github.com/senvenluckys/toAss.git
          cd toAss
          pip install -r requirements.txt
          python toAss.py
          ```
        files: |
          artifacts/windows-executable/*
          artifacts/macos-executable/*

